version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Mật khẩu root
      MYSQL_DATABASE: mydb               # Tạo database
      MYSQL_USER: sa                   # Tạo user
      MYSQL_PASSWORD: sa123456           # Mật khẩu user
    volumes:
      - mysql_data:/var/lib/mysql        # Mount volume vào thư mục MySQL
    ports:
      - "3306:3306"                      # Map cổng 3306

volumes:
  mysql_data:                            # Khai báo volume