version: '3.8'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin      # Tài khoản admin MongoDB
      MONGO_INITDB_ROOT_PASSWORD: adminpass  # Mật khẩu admin
    volumes:
      - mongodb_data:/data/db                # Lưu trữ dữ liệu MongoDB
    networks:
      - mongo_network

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"                          # Truy cập Mongo Express qua cổng 8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin  # Tài khoản admin MongoDB
      ME_CONFIG_MONGODB_ADMINPASSWORD: adminpass
      ME_CONFIG_MONGODB_SERVER: mongodb       # Tên service MongoDB
    depends_on:
      - mongodb
    networks:
      - mongo_network

volumes:
  mongodb_data:                               # Volume cho MongoDB

networks:
  mongo_network:                              # Mạng riêng cho các services