# Sử dụng image Nginx mới nhất làm base image
FROM nginx:latest

# Copy file index.html vào thư mục chứa trang web của Nginx
COPY index.html /usr/share/nginx/html/index.html

# Expose cổng 80 để phục vụ web
EXPOSE 80
