version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword 
      MYSQL_DATABASE: mydb               
      MYSQL_USER: sa                   
      MYSQL_PASSWORD: sa123456           
    volumes:
      - mysql_data:/var/lib/mysql        
    ports:
      - "3306:3306"                     
volumes:
  mysql_data:                            